"""update

Revision ID: df242e1754fe
Revises: f6ffc878e236
Create Date: 2023-10-19 16:48:17.943060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df242e1754fe'
down_revision = 'f6ffc878e236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
